;//Map header file for CHM project
;//Automatically generated by Easy CHM.
;//Website : http://www.zipghost.com
;//Email   : webmaster@zipghost.com
;//Date    : 2016/10/18 20:29:48

;//NOTE:
;//All strings after the ";" are commnets, they will be ignored by the CHM Compiler.

#define IDH_1000	1000	; Evernote Export 1.1 课程介绍 & 机器学习介绍.html
#define IDH_1001	1001	; Evernote Export 1.2 深度学习(Deep Learning)介绍.html
#define IDH_1002	1002	; Evernote Export 2 基本概念 (Basic Concepts).html
#define IDH_1003	1003	; Evernote Export 3.1 决策树(decision tree)算法.html
#define IDH_1004	1004	; Evernote Export 3.2 决策树(decision tree)应用.html
#define IDH_1005	1005	; Evernote Export 4.1 最邻近规则分类(K-Nearest Neighbor)KNN算法.html
#define IDH_1006	1006	; Evernote Export 4.2 最邻近规则分类(K-Nearest Neighbor)KNN算法应用.html
#define IDH_1007	1007	; Evernote Export 5.1 支持向量机(SVM)算法（上）.html
#define IDH_1008	1008	; Evernote Export 5.1 支持向量机(SVM)算法（上）应用.html
#define IDH_1009	1009	; Evernote Export 5.2 支持向量机(SVM)算法（下）.html
#define IDH_1010	1010	; Evernote Export 5.3 支持向量机(SVM)算法（下）应用.html
#define IDH_1011	1011	; Evernote Export 6.1 神经网络算法(Nerual Networks)（上）.html
#define IDH_1012	1012	; Evernote Export 6.2 神经网络算法(Nerual Networks)应用(上）.html
#define IDH_1013	1013	; Evernote Export 6.3 神经网络算法(Nerual Networks)应用(下）.html
#define IDH_1014	1014	; Evernote Export 7.1 简单线性回归 (Simple Linear Regression)上.html
#define IDH_1015	1015	; Evernote Export 7.1 简单线性回归 (Simple Linear Regression)下.html
#define IDH_1016	1016	; Evernote Export 7.3　多元回归分析(multiple regression).html
#define IDH_1017	1017	; Evernote Export 7.4　多元回归分析(multiple regression)应用.html
#define IDH_1018	1018	; Evernote Export 7.5 非线性回归 logistic regression.html
#define IDH_1019	1019	; Evernote Export 7.6 非线性回归应用：losgistic regression application.html
#define IDH_1020	1020	; Evernote Export 7.7 回归中的相关度和R平方值.html
#define IDH_1021	1021	; Evernote Export 7.8 回归中的相关度和R平方值应用.html
#define IDH_1022	1022	; Evernote Export 8.1 聚类(Clustering) K-means算法.html
#define IDH_1023	1023	; Evernote Export 8.2 聚类(Clustering) K-means算法应用.html
#define IDH_1024	1024	; Evernote Export 8.3 聚类(Clustering) hierarchical clustering 层次聚类.html
#define IDH_1025	1025	; Evernote Export 8.4 聚类(Clustering) hierarchical clustering 层次聚类应用.html
