;//Alias header file for CHM project
;//Automatically generated by Easy CHM.
;//Website : http://www.zipghost.com
;//Email   : webmaster@zipghost.com
;//Date    : 2016/10/18 20:29:48

;//NOTE:
;//All strings after the ";" are commnets, they will be ignored by the CHM Compiler.

IDH_1000=1.1 课程介绍 & 机器学习介绍.html	; Evernote Export
IDH_1001=1.2 深度学习(Deep Learning)介绍.html	; Evernote Export
IDH_1002=2 基本概念 (Basic Concepts).html	; Evernote Export
IDH_1003=3.1 决策树(decision tree)算法.html	; Evernote Export
IDH_1004=3.2 决策树(decision tree)应用.html	; Evernote Export
IDH_1005=4.1 最邻近规则分类(K-Nearest Neighbor)KNN算法.html	; Evernote Export
IDH_1006=4.2 最邻近规则分类(K-Nearest Neighbor)KNN算法应用.html	; Evernote Export
IDH_1007=5.1 支持向量机(SVM)算法（上）.html	; Evernote Export
IDH_1008=5.1 支持向量机(SVM)算法（上）应用.html	; Evernote Export
IDH_1009=5.2 支持向量机(SVM)算法（下）.html	; Evernote Export
IDH_1010=5.3 支持向量机(SVM)算法（下）应用.html	; Evernote Export
IDH_1011=6.1 神经网络算法(Nerual Networks)（上）.html	; Evernote Export
IDH_1012=6.2 神经网络算法(Nerual Networks)应用(上）.html	; Evernote Export
IDH_1013=6.3 神经网络算法(Nerual Networks)应用(下）.html	; Evernote Export
IDH_1014=7.1 简单线性回归 (Simple Linear Regression)上.html	; Evernote Export
IDH_1015=7.1 简单线性回归 (Simple Linear Regression)下.html	; Evernote Export
IDH_1016=7.3　多元回归分析(multiple regression).html	; Evernote Export
IDH_1017=7.4　多元回归分析(multiple regression)应用.html	; Evernote Export
IDH_1018=7.5 非线性回归 logistic regression.html	; Evernote Export
IDH_1019=7.6 非线性回归应用：losgistic regression application.html	; Evernote Export
IDH_1020=7.7 回归中的相关度和R平方值.html	; Evernote Export
IDH_1021=7.8 回归中的相关度和R平方值应用.html	; Evernote Export
IDH_1022=8.1 聚类(Clustering) K-means算法.html	; Evernote Export
IDH_1023=8.2 聚类(Clustering) K-means算法应用.html	; Evernote Export
IDH_1024=8.3 聚类(Clustering) hierarchical clustering 层次聚类.html	; Evernote Export
IDH_1025=8.4 聚类(Clustering) hierarchical clustering 层次聚类应用.html	; Evernote Export
